In [1301]:
import pandas as pd

In [1302]:
# Importing different datasets
path1 = r"C:\Users\giang\OneDrive\Documenti\GitHub\world_cup_project\data\results.csv"
with open(path1) as file:
    results = pd.read_csv(file)

path2 = r"C:\Users\giang\OneDrive\Documenti\GitHub\world_cup_project\data\train.csv"
with open(path2) as file:
    train = pd.read_csv(file)

path3 = r"C:\Users\giang\OneDrive\Documenti\GitHub\world_cup_project\data\test.csv"
with open(path3) as file:
    test = pd.read_csv(file)

path4 = r"C:\Users\giang\OneDrive\Documenti\GitHub\world_cup_project\data\shootouts.csv"
with open(path4) as file:
    shootouts = pd.read_csv(file)

path = r"C:\Users\giang\OneDrive\Documenti\GitHub\world_cup_project\data\to_confront_FIFA_ranking.csv"
with open(path) as file:
    confront = pd.read_csv(file)

In [1303]:
# Having a closer look at "confront"
print(confront.shape)
print(confront.columns)
print(confront.dtypes)

(23921, 25)
Index(['date', 'home_team', 'away_team', 'home_team_continent',
       'away_team_continent', 'home_team_fifa_rank', 'away_team_fifa_rank',
       'home_team_total_fifa_points', 'away_team_total_fifa_points',
       'home_team_score', 'away_team_score', 'tournament', 'city', 'country',
       'neutral_location', 'shoot_out', 'home_team_result',
       'home_team_goalkeeper_score', 'away_team_goalkeeper_score',
       'home_team_mean_defense_score', 'home_team_mean_offense_score',
       'home_team_mean_midfield_score', 'away_team_mean_defense_score',
       'away_team_mean_offense_score', 'away_team_mean_midfield_score'],
      dtype='object')
date                              object
home_team                         object
away_team                         object
home_team_continent               object
away_team_continent               object
home_team_fifa_rank                int64
away_team_fifa_rank                int64
home_team_total_fifa_points        int64
away_team_total_fifa_points        int64
home_team_score                    int64
away_team_score                    int64
tournament                        object
city                              object
country                           object
neutral_location                    bool
shoot_out                         object
home_team_result                  object
home_team_goalkeeper_score       float64
away_team_goalkeeper_score       float64
home_team_mean_defense_score     float64
home_team_mean_offense_score     float64
home_team_mean_midfield_score    float64
away_team_mean_defense_score     float64
away_team_mean_offense_score     float64
away_team_mean_midfield_score    float64
dtype: object

In [1304]:
confront.tail()
# It does not have data of 2026 World Cup, so let's ignore it

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,shoot_out,home_team_result,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
23916,2022-06-14,Moldova,Andorra,Europe,Europe,180,153,932,1040,2,...,No,Win,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23917,2022-06-14,Liechtenstein,Latvia,Europe,Europe,192,135,895,1105,0,...,No,Lose,NaN,65.0,NaN,NaN,NaN,NaN,NaN,NaN
23918,2022-06-14,Chile,Ghana,South America,Africa,28,60,1526,1387,0,...,Yes,Lose,79.0,74.0,75.5,76.7,78.2,75.5,76.0,78.2
23919,2022-06-14,Japan,Tunisia,Asia,Africa,23,35,1553,1499,0,...,No,Lose,73.0,NaN,75.2,75.0,77.5,70.8,72.3,74.0
23920,2022-06-14,Korea Republic,Egypt,Asia,Africa,29,32,1519,1500,4,...,No,Win,75.0,NaN,73.0,80.0,73.8,NaN,79.3,70.8

In [1305]:
# Let's see "results"
print(results.columns)
results.tail()

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49500,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,2.0,0.0,FIFA World Cup,Foxborough,United States,True
49502,2026-07-10,Spain,Belgium,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49503,2026-07-11,Norway,England,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49504,2026-07-11,Argentina,Switzerland,NaN,NaN,FIFA World Cup,Kansas City,United States,True

In [1306]:
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [1307]:
# Drop rows until 2006
results = results[results["date"] > "2006-01-01"]
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
29732,2006-01-02,Qatar,Libya,2.0,0.0,Friendly,Doha,Qatar,False
29733,2006-01-05,Egypt,Zimbabwe,2.0,0.0,Friendly,Alexandria,Egypt,False
29734,2006-01-07,Guinea,Togo,1.0,0.0,Friendly,Viry-Châtillon,France,True
29735,2006-01-09,Morocco,DR Congo,3.0,0.0,Friendly,Rabat,Morocco,False
29736,2006-01-11,Ghana,Togo,0.0,1.0,Friendly,Monastir,Tunisia,True

In [1308]:
# Drop latest matches that are not played yet
results.dropna(inplace = True)
results.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49497,2026-07-06,Portugal,Spain,0.0,1.0,FIFA World Cup,Dallas,United States,True
49498,2026-07-06,United States,Belgium,1.0,4.0,FIFA World Cup,Seattle,United States,False
49499,2026-07-07,Argentina,Egypt,3.0,2.0,FIFA World Cup,Atlanta,United States,True
49500,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,2.0,0.0,FIFA World Cup,Foxborough,United States,True

In [1309]:
# selecting only World Cup mathces
results = results[results["tournament"] == "FIFA World Cup"]
print(results.shape)
results.head()

(417, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
30037,2006-06-09,Germany,Costa Rica,4.0,2.0,FIFA World Cup,Munich,Germany,False
30038,2006-06-09,Poland,Ecuador,0.0,2.0,FIFA World Cup,Gelsenkirchen,Germany,True
30039,2006-06-10,Argentina,Ivory Coast,2.0,1.0,FIFA World Cup,Hamburg,Germany,True
30040,2006-06-10,England,Paraguay,1.0,0.0,FIFA World Cup,Frankfurt,Germany,True
30041,2006-06-10,Trinidad and Tobago,Sweden,0.0,0.0,FIFA World Cup,Dortmund,Germany,True

In [1310]:
# Drop irrelevant columns
results.drop(columns=["tournament", "city", "country", "neutral"], inplace=True)
results.tail()

             date      home_team away_team  home_score  away_score
49497  2026-07-06       Portugal     Spain         0.0         1.0
49498  2026-07-06  United States   Belgium         1.0         4.0
49499  2026-07-07      Argentina     Egypt         3.0         2.0
49500  2026-07-07    Switzerland  Colombia         0.0         0.0
49501  2026-07-09         France   Morocco         2.0         0.0

In [1311]:
# Here knockout matches which ended up at shootout are marked as draws since home_score = away_score
# Thus I need another dataset (shootouts) to deal with it
path = r"C:\Users\giang\OneDrive\Documenti\GitHub\world_cup_project\data\shootouts.csv"
with open(path) as file:
    shootouts = pd.read_csv(file)
shootouts.columns
shootouts.tail()

           date    home_team away_team       winner first_shooter
677  2026-06-06    Lithuania    Latvia    Lithuania     Lithuania
678  2026-06-29      Germany  Paraguay     Paraguay       Germany
679  2026-06-29  Netherlands   Morocco      Morocco   Netherlands
680  2026-07-03    Australia     Egypt        Egypt     Australia
681  2026-07-07  Switzerland  Colombia  Switzerland      Colombia

In [1312]:
shootouts.iloc[678, 1], shootouts.iloc[678, -2]

('Germany', 'Paraguay')

In [1313]:
type(shootouts.iloc[678, 1]), type(shootouts.iloc[678, -2])

(str, str)

In [1314]:
shootouts.iloc[678, 1] == shootouts.iloc[678, -2]

False

In [1315]:
# Transform "winner" to a binary variables as the model does not accept strings

shootouts["result"] = 1 # away_team wins
for i in range(shootouts.shape[0]):
    if shootouts.iloc[i, 3] == shootouts.iloc[i, 1]: # 3 is "winner", 1 is "home_team"
        shootouts.iloc[i, -1] = 0 # -1 is "result"
    else:
        pass
shootouts.drop(columns="winner", inplace=True)
shootouts.tail()

           date    home_team away_team first_shooter  result
677  2026-06-06    Lithuania    Latvia     Lithuania       0
678  2026-06-29      Germany  Paraguay       Germany       1
679  2026-06-29  Netherlands   Morocco   Netherlands       1
680  2026-07-03    Australia     Egypt     Australia       1
681  2026-07-07  Switzerland  Colombia      Colombia       0

In [1316]:
# Considering only world cups from 2006
shootouts = shootouts[shootouts["date"] > "2006-01-01"]
shootouts.head()

           date home_team    away_team first_shooter  result
371  2006-02-04   Nigeria      Tunisia       Nigeria       0
372  2006-02-04  Cameroon  Ivory Coast      Cameroon       1
373  2006-02-10     Egypt  Ivory Coast         Egypt       0
374  2006-02-28   Finland   Kazakhstan           NaN       1
375  2006-03-01   Finland      Belarus           NaN       0

In [1317]:
# dropping first_team as it cointains NaN values and it is the only feature related to the shootouts.
# Thus it is useless to manage NaN values of other matches just for this feature
shootouts.drop(columns="first_shooter", inplace=True)
shootouts.head()

           date home_team    away_team  result
371  2006-02-04   Nigeria      Tunisia       0
372  2006-02-04  Cameroon  Ivory Coast       1
373  2006-02-10     Egypt  Ivory Coast       0
374  2006-02-28   Finland   Kazakhstan       1
375  2006-03-01   Finland      Belarus       0

In [1318]:
# Merging "results" and "shootouts"
# I didn't dropped rows relative to other comptetitions in "shootouts" as with the merge they will be gone anyway
data_matches = pd.merge(results, shootouts, left_on=["date", "home_team", "away_team"], right_on=["date", "home_team", "away_team"], how="left")
data_matches.head()

,date,home_team,away_team,home_score,away_score,result
0,2006-06-09,Germany,Costa Rica,4.0,2.0,NaN
1,2006-06-09,Poland,Ecuador,0.0,2.0,NaN
2,2006-06-10,Argentina,Ivory Coast,2.0,1.0,NaN
3,2006-06-10,England,Paraguay,1.0,0.0,NaN
4,2006-06-10,Trinidad and Tobago,Sweden,0.0,0.0,NaN

In [1319]:
# testing if the merge was done correctly
data_matches[:][data_matches["date"] == "2026-06-29"]
# ok it is correct

           date    home_team away_team  home_score  away_score  result
393  2026-06-29       Brazil     Japan         2.0         1.0     NaN
394  2026-06-29      Germany  Paraguay         1.0         1.0     1.0
395  2026-06-29  Netherlands   Morocco         1.0         1.0     1.0

In [ ]:
# now let's add a dummy feature to encode if the match ended up with shootout
data_matches["shootouts"] = 0
for i in range(data_matches.shape[0]):
    if data_matches.iloc[i, 3] == data_matches.iloc[i, 4]: # the two scores are even
        data_matches.iloc[i, -1] = 1 # match to shootout
    else:
        pass
data_matches.head()

,date,home_team,away_team,home_score,away_score,result,shootouts
0,2006-06-09,Germany,Costa Rica,4.0,2.0,NaN,0
1,2006-06-09,Poland,Ecuador,0.0,2.0,NaN,0
2,2006-06-10,Argentina,Ivory Coast,2.0,1.0,NaN,0
3,2006-06-10,England,Paraguay,1.0,0.0,NaN,0
4,2006-06-10,Trinidad and Tobago,Sweden,0.0,0.0,NaN,1

In [1321]:
# testing if it is correct
data_matches[:][data_matches["date"] == "2026-06-29"]

,date,home_team,away_team,home_score,away_score,result,shootouts
393,2026-06-29,Brazil,Japan,2.0,1.0,NaN,0
394,2026-06-29,Germany,Paraguay,1.0,1.0,1.0,1
395,2026-06-29,Netherlands,Morocco,1.0,1.0,1.0,1

In [ ]:
# managing "winner" for other matches ended in 90 mins
for i in range(data_matches.shape[0]):
    if pd.isnull(data_matches.iloc[i, -2]): # matche did not finished with shootout
        if data_matches.iloc[i, 3] > data_matches.iloc[i, 4]: # first team beated the second
            data_matches.iloc[i, -2] = 0 # home_team wins
        elif data_matches.iloc[i, 3] < data_matches.iloc[i, 4]:
            data_matches.iloc[i, -2] = 1 # away_team wins
        else:
            data_matches.iloc[i, -2] = 2 # draw
    else:
        pass
data_matches.tail(15)

,date,home_team,away_team,home_score,away_score,result,shootouts
0,2006-06-09,Germany,Costa Rica,4.0,2.0,0.0,0
1,2006-06-09,Poland,Ecuador,0.0,2.0,1.0,0
2,2006-06-10,Argentina,Ivory Coast,2.0,1.0,0.0,0
3,2006-06-10,England,Paraguay,1.0,0.0,0.0,0
4,2006-06-10,Trinidad and Tobago,Sweden,0.0,0.0,2.0,1

In [1323]:
# Let's see "train"
print(train.shape)
train.columns
# it has some new relevant features

(192, 24)

Index(['version', 'team', 'continent', 'is_host', 'goals_scored_last_4y',
       'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y',
       'draws_last_4y', 'world_cup_titles_before',
       'squad_total_market_value_eur', 'fifa_rank_pre_tournament',
       'fifa_points_pre_tournament', 'squad_avg_age',
       'world_cup_participations_before', 'groups_passed_before',
       'round16_before', 'quarterfinals_before', 'semifinals_before',
       'finals_before', 'winner', 'finalist', 'semi_finalist',
       'quarter_finalist'],
      dtype='object')

In [1324]:
# Extracting only relevant features and basic colums
# i.e. dropping the remaining
train = train.drop(columns = ["continent", "fifa_rank_pre_tournament", "fifa_points_pre_tournament", 
                             "finalist", "semi_finalist", "quarter_finalist"])
# fifa_rank_pre_torunment could have been useful but in "confront" I already have fifa rank updated at every match
train.columns

Index(['version', 'team', 'is_host', 'goals_scored_last_4y',
       'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y',
       'draws_last_4y', 'world_cup_titles_before',
       'squad_total_market_value_eur', 'squad_avg_age',
       'world_cup_participations_before', 'groups_passed_before',
       'round16_before', 'quarterfinals_before', 'semifinals_before',
       'finals_before', 'winner'],
      dtype='object')

In [1325]:
# Doing same cleaning on "test" as they are the same dataset, but for different time horizons
test = test.drop(columns = ["continent", "fifa_rank_pre_tournament", "fifa_points_pre_tournament", 
                            "finalist", "semi_finalist", "quarter_finalist"])
test.columns

Index(['version', 'team', 'is_host', 'goals_scored_last_4y',
       'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y',
       'draws_last_4y', 'world_cup_titles_before',
       'squad_total_market_value_eur', 'squad_avg_age',
       'world_cup_participations_before', 'groups_passed_before',
       'round16_before', 'quarterfinals_before', 'semifinals_before',
       'finals_before', 'winner'],
      dtype='object')

In [1326]:
# Merging the three datasets
# First rebuild the entire dataset from "train" and "test"
data_teams = pd.concat([train, test])
data_teams.columns, data_teams.shape

(Index(['version', 'team', 'is_host', 'goals_scored_last_4y',
        'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y',
        'draws_last_4y', 'world_cup_titles_before',
        'squad_total_market_value_eur', 'squad_avg_age',
        'world_cup_participations_before', 'groups_passed_before',
        'round16_before', 'quarterfinals_before', 'semifinals_before',
        'finals_before', 'winner'],
       dtype='object'),
 (240, 18))

In [1327]:
train.iloc[22, :] # Serbia
# I have modified "test" since first it was written "Serbia and Montenegro" thus the merge did not work correctly
# and I got some NaN in df

version                                   2006
team                                    Serbia
is_host                                      0
goals_scored_last_4y                        46
goals_received_last_4y                      42
wins_last_4y                                13
losses_last_4y                              13
draws_last_4y                               12
world_cup_titles_before                      0
squad_total_market_value_eur       294500000.0
squad_avg_age                             26.9
world_cup_participations_before              9
groups_passed_before                         7
round16_before                               2
quarterfinals_before                         5
semifinals_before                            2
finals_before                                0
winner                                       0
Name: 22, dtype: object

In [1328]:
test.iloc[-3, :] # Curacao
# I have modified "test" since first it was written "Cura?o" thus the merge did not work correctly
# and I got some NaN in df

version                                2026
team                                Curaçao
is_host                                   0
goals_scored_last_4y                     55
goals_received_last_4y                   39
wins_last_4y                             12
losses_last_4y                           10
draws_last_4y                            10
world_cup_titles_before                   0
squad_total_market_value_eur       25380000
squad_avg_age                          26.5
world_cup_participations_before           0
groups_passed_before                      0
round16_before                            0
quarterfinals_before                      0
semifinals_before                         0
finals_before                             0
winner                                  NaN
Name: 45, dtype: object

In [ ]:
# Preparing datasets for the merge
# Extracting "year" from "date" in "data_matches"
data_matches[["year", "month", "day"]] = data_matches["date"].str.split("-", expand=True)
data_matches.drop(columns=["date"], inplace=True)
data_matches.columns

Index(['home_team', 'away_team', 'home_score', 'away_score', 'result',
       'shootouts', 'year', 'month', 'day'],
      dtype='object')

In [ ]:
# changing type of "year" in confront to match the one in "data_teams"
data_matches["year"] = pd.to_numeric(data_matches["year"])
data_matches.dtypes

home_team      object
away_team      object
home_score    float64
away_score    float64
result        float64
shootouts       int64
year            int64
month          object
day            object
dtype: object

In [1331]:
# Merging
df = pd.merge(data_matches, data_teams, left_on=["year", "home_team"], right_on = ["version", "team"], how="left").drop(columns = ["version", "team"])
df.rename(columns={
    "is_host": "home_is_host",
    "goals_scored_last_4y": "home_goals_scored_last_4y",
    "goals_received_last_4y": "home_goals_received_last_4y", 
    "wins_last_4y": "home_wins_last_4y",
    "losses_last_4y": "home_losses_last_4y",
    "draws_last_4y": "home_draws_last_4y",
    "world_cup_titles_before": "home_wc_titles_before",
    "squad_total_market_value_eur": "home_total_market_value_eur",
    "world_cup_participations_before": "home_wc_participations_before",
    "squad_avg_age": "home_avg_age",
    "groups_passed_before": "home_groups_passed_before",
    "round16_before": "home_round16_before",
    "quarterfinals_before": "home_quarterfinals_before",
    "semifinals_before": "home_semifinals_before",
    "finals_before": "home_finals_before"
}, inplace=True)

df = pd.merge(df, data_teams, left_on=["year", "away_team"], right_on = ["version", "team"], how="left").drop(columns = ["version", "team"])
df.rename(columns={
    "is_host": "away_is_host",
    "goals_scored_last_4y": "away_goals_scored_last_4y",
    "goals_received_last_4y": "away_goals_received_last_4y", 
    "wins_last_4y": "away_wins_last_4y",
    "losses_last_4y": "away_losses_last_4y",
    "draws_last_4y": "away_draws_last_4y",
    "world_cup_titles_before": "away_wc_titles_before",
    "squad_total_market_value_eur": "away_total_market_value_eur",
    "world_cup_participations_before": "away_wc_participations_before",
    "squad_avg_age": "away_avg_age",
    "groups_passed_before": "away_groups_passed_before",
    "round16_before": "away_round16_before",
    "quarterfinals_before": "away_quarterfinals_before",
    "semifinals_before": "away_semifinals_before",
    "finals_before": "away_finals_before"
}, inplace=True)
df.columns

Index(['home_team', 'away_team', 'home_score', 'away_score', 'result',
       'shootouts', 'year', 'month', 'day', 'home_is_host',
       'home_goals_scored_last_4y', 'home_goals_received_last_4y',
       'home_wins_last_4y', 'home_losses_last_4y', 'home_draws_last_4y',
       'home_wc_titles_before', 'home_total_market_value_eur', 'home_avg_age',
       'home_wc_participations_before', 'home_groups_passed_before',
       'home_round16_before', 'home_quarterfinals_before',
       'home_semifinals_before', 'home_finals_before', 'winner_x',
       'away_is_host', 'away_goals_scored_last_4y',
       'away_goals_received_last_4y', 'away_wins_last_4y',
       'away_losses_last_4y', 'away_draws_last_4y', 'away_wc_titles_before',
       'away_total_market_value_eur', 'away_avg_age',
       'away_wc_participations_before', 'away_groups_passed_before',
       'away_round16_before', 'away_quarterfinals_before',
       'away_semifinals_before', 'away_finals_before', 'winner_y'],
      dtype='object')

In [1332]:
# Swapping columns to give them a better order
new_columns_list = ['year', 'month', 'day', 'home_team', 'away_team', 'result', 'shootouts',
       'home_score', 'home_is_host', 'home_goals_scored_last_4y',
       'home_goals_received_last_4y', 'home_wins_last_4y', 'home_losses_last_4y', 'home_draws_last_4y', 
       'home_wc_titles_before', 'home_total_market_value_eur', 'home_avg_age', 'home_wc_participations_before', 
       'home_groups_passed_before', 'home_round16_before', 'home_quarterfinals_before', 'home_semifinals_before', 'home_finals_before',
       'away_score', 'away_is_host', 'away_goals_scored_last_4y', 'away_goals_received_last_4y',
       'away_wins_last_4y', 'away_losses_last_4y', 'away_draws_last_4y', 'away_wc_titles_before', 'away_total_market_value_eur',
       'away_avg_age', 'away_wc_participations_before', 'away_groups_passed_before',
       'away_round16_before', 'away_quarterfinals_before', 'away_semifinals_before', 'away_finals_before']
df = df[new_columns_list]

In [1333]:
# checking if there are some NaN in "df"
container = list()
for j in range(df.shape[0]):
    count = 0 # counts only the first column so "container" is not too much long
    for i in df.columns:
        if count == 0:
            if df[i].isna().iloc[j]:
                count += 1
                container.append(f"Missing value at row {j} column {i}")
            else:
                pass
        else:
            pass
print(container)
print(len(container))

[]
0

In [1334]:
# A list of matches with some NaN at first detected by the code above,
# but then corrected directly modifing "train" and "test"

In [1335]:
df.iloc[7, :]

year                                    2006
month                                     06
day                                       11
home_team                             Serbia
away_team                        Netherlands
result                                   1.0
shootouts                                  0
home_score                               0.0
home_is_host                               0
home_goals_scored_last_4y                 46
home_goals_received_last_4y               42
home_wins_last_4y                         13
home_losses_last_4y                       13
home_draws_last_4y                        12
home_wc_titles_before                      0
home_total_market_value_eur      294500000.0
home_avg_age                            26.9
home_wc_participations_before              9
home_groups_passed_before                  7
home_round16_before                        2
home_quarterfinals_before                  5
home_semifinals_before                     2
home_finals_before                         0
away_score                               1.0
away_is_host                               0
away_goals_scored_last_4y                 88
away_goals_received_last_4y               30
away_wins_last_4y                         28
away_losses_last_4y                        7
away_draws_last_4y                        12
away_wc_titles_before                      0
away_total_market_value_eur      766000000.0
away_avg_age                            27.0
away_wc_participations_before              7
away_groups_passed_before                  7
away_round16_before                        5
away_quarterfinals_before                  4
away_semifinals_before                     3
away_finals_before                         2
Name: 7, dtype: object

In [1336]:
df.iloc[20, :]

year                                    2006
month                                     06
day                                       16
home_team                          Argentina
away_team                             Serbia
result                                   0.0
shootouts                                  0
home_score                               6.0
home_is_host                               0
home_goals_scored_last_4y                 97
home_goals_received_last_4y               55
home_wins_last_4y                         31
home_losses_last_4y                       10
home_draws_last_4y                        10
home_wc_titles_before                      2
home_total_market_value_eur      777200000.0
home_avg_age                            27.8
home_wc_participations_before             13
home_groups_passed_before                 10
home_round16_before                        5
home_quarterfinals_before                  6
home_semifinals_before                     4
home_finals_before                         4
away_score                               0.0
away_is_host                               0
away_goals_scored_last_4y                 46
away_goals_received_last_4y               42
away_wins_last_4y                         13
away_losses_last_4y                       13
away_draws_last_4y                        12
away_wc_titles_before                      0
away_total_market_value_eur      294500000.0
away_avg_age                            26.9
away_wc_participations_before              9
away_groups_passed_before                  7
away_round16_before                        2
away_quarterfinals_before                  5
away_semifinals_before                     2
away_finals_before                         0
Name: 20, dtype: object

In [1337]:
df.iloc[37, :]

year                                    2006
month                                     06
day                                       21
home_team                        Ivory Coast
away_team                             Serbia
result                                   0.0
shootouts                                  0
home_score                               3.0
home_is_host                               0
home_goals_scored_last_4y                 67
home_goals_received_last_4y               34
home_wins_last_4y                         21
home_losses_last_4y                        8
home_draws_last_4y                         8
home_wc_titles_before                      0
home_total_market_value_eur      410900000.0
home_avg_age                            25.8
home_wc_participations_before              0
home_groups_passed_before                  0
home_round16_before                        0
home_quarterfinals_before                  0
home_semifinals_before                     0
home_finals_before                         0
away_score                               2.0
away_is_host                               0
away_goals_scored_last_4y                 46
away_goals_received_last_4y               42
away_wins_last_4y                         13
away_losses_last_4y                       13
away_draws_last_4y                        12
away_wc_titles_before                      0
away_total_market_value_eur      294500000.0
away_avg_age                            26.9
away_wc_participations_before              9
away_groups_passed_before                  7
away_round16_before                        2
away_quarterfinals_before                  5
away_semifinals_before                     2
away_finals_before                         0
Name: 37, dtype: object

In [1338]:
df.loc[328, :]

year                                    2026
month                                     06
day                                       14
home_team                            Germany
away_team                            Curaçao
result                                   0.0
shootouts                                  0
home_score                               7.0
home_is_host                               0
home_goals_scored_last_4y                 80
home_goals_received_last_4y               47
home_wins_last_4y                         21
home_losses_last_4y                       10
home_draws_last_4y                         7
home_wc_titles_before                      4
home_total_market_value_eur      828000000.0
home_avg_age                            26.6
home_wc_participations_before             20
home_groups_passed_before                 18
home_round16_before                       10
home_quarterfinals_before                 16
home_semifinals_before                    13
home_finals_before                         8
away_score                               1.0
away_is_host                               0
away_goals_scored_last_4y                 55
away_goals_received_last_4y               39
away_wins_last_4y                         12
away_losses_last_4y                       10
away_draws_last_4y                        10
away_wc_titles_before                      0
away_total_market_value_eur       25380000.0
away_avg_age                            26.5
away_wc_participations_before              0
away_groups_passed_before                  0
away_round16_before                        0
away_quarterfinals_before                  0
away_semifinals_before                     0
away_finals_before                         0
Name: 328, dtype: object

In [1339]:
df.loc[353, :]

year                                    2026
month                                     06
day                                       20
home_team                            Ecuador
away_team                            Curaçao
result                                   2.0
shootouts                                  1
home_score                               0.0
home_is_host                               0
home_goals_scored_last_4y                 39
home_goals_received_last_4y               23
home_wins_last_4y                         16
home_losses_last_4y                        6
home_draws_last_4y                        15
home_wc_titles_before                      0
home_total_market_value_eur      349580000.0
home_avg_age                            25.2
home_wc_participations_before              4
home_groups_passed_before                  1
home_round16_before                        1
home_quarterfinals_before                  0
home_semifinals_before                     0
home_finals_before                         0
away_score                               0.0
away_is_host                               0
away_goals_scored_last_4y                 55
away_goals_received_last_4y               39
away_wins_last_4y                         12
away_losses_last_4y                       10
away_draws_last_4y                        10
away_wc_titles_before                      0
away_total_market_value_eur       25380000.0
away_avg_age                            26.5
away_wc_participations_before              0
away_groups_passed_before                  0
away_round16_before                        0
away_quarterfinals_before                  0
away_semifinals_before                     0
away_finals_before                         0
Name: 353, dtype: object

In [1340]:
df.iloc[376, :]

year                                    2026
month                                     06
day                                       25
home_team                            Curaçao
away_team                        Ivory Coast
result                                   1.0
shootouts                                  0
home_score                               0.0
home_is_host                               0
home_goals_scored_last_4y                 55
home_goals_received_last_4y               39
home_wins_last_4y                         12
home_losses_last_4y                       10
home_draws_last_4y                        10
home_wc_titles_before                      0
home_total_market_value_eur       25380000.0
home_avg_age                            26.5
home_wc_participations_before              0
home_groups_passed_before                  0
home_round16_before                        0
home_quarterfinals_before                  0
home_semifinals_before                     0
home_finals_before                         0
away_score                               2.0
away_is_host                               0
away_goals_scored_last_4y                 79
away_goals_received_last_4y               29
away_wins_last_4y                         27
away_losses_last_4y                        8
away_draws_last_4y                         8
away_wc_titles_before                      0
away_total_market_value_eur      370800000.0
away_avg_age                            26.6
away_wc_participations_before              3
away_groups_passed_before                  0
away_round16_before                        0
away_quarterfinals_before                  0
away_semifinals_before                     0
away_finals_before                         0
Name: 376, dtype: object

In [1341]:
# last look at the data before training
print(df.shape)
df.columns

(417, 39)

Index(['year', 'month', 'day', 'home_team', 'away_team', 'result', 'shootouts',
       'home_score', 'home_is_host', 'home_goals_scored_last_4y',
       'home_goals_received_last_4y', 'home_wins_last_4y',
       'home_losses_last_4y', 'home_draws_last_4y', 'home_wc_titles_before',
       'home_total_market_value_eur', 'home_avg_age',
       'home_wc_participations_before', 'home_groups_passed_before',
       'home_round16_before', 'home_quarterfinals_before',
       'home_semifinals_before', 'home_finals_before', 'away_score',
       'away_is_host', 'away_goals_scored_last_4y',
       'away_goals_received_last_4y', 'away_wins_last_4y',
       'away_losses_last_4y', 'away_draws_last_4y', 'away_wc_titles_before',
       'away_total_market_value_eur', 'away_avg_age',
       'away_wc_participations_before', 'away_groups_passed_before',
       'away_round16_before', 'away_quarterfinals_before',
       'away_semifinals_before', 'away_finals_before'],
      dtype='object')

In [1342]:
# Training
# selecting features and target
features = df[['year', 'shootouts', 'home_is_host', 'home_goals_scored_last_4y',
       'home_goals_received_last_4y', 'home_wins_last_4y',
       'home_losses_last_4y', 'home_draws_last_4y', 'home_wc_titles_before',
       'home_total_market_value_eur', 'home_avg_age',
       'home_wc_participations_before', 'home_groups_passed_before',
       'home_round16_before', 'home_quarterfinals_before',
       'home_semifinals_before', 'home_finals_before',
       'away_is_host', 'away_goals_scored_last_4y',
       'away_goals_received_last_4y', 'away_wins_last_4y',
       'away_losses_last_4y', 'away_draws_last_4y', 'away_wc_titles_before',
       'away_total_market_value_eur', 'away_avg_age',
       'away_wc_participations_before', 'away_groups_passed_before',
       'away_round16_before', 'away_quarterfinals_before',
       'away_semifinals_before', 'away_finals_before']] 
target = df[['year', 'result']]

In [ ]:
# Using Logistic regression 
# Accuracy and loss are computed on the train set

# to be modified: now it outputs a binary variable (it is totally wrong), I should implement a softmax regression with 3 classes
# try a ridge regularization and see what happens, first it is essential to standardize continous variables

from sklearn.metrics import accuracy_score, log_loss
from sklearn.linear_model import LogisticRegression

X_train = features[(features['year'] != 2026)].drop(columns=['year'])
Y_train = target.loc[target['year'] != 2026, 'result']

X_test = features[(features['year'] == 2026)].drop(columns=['year'])
Y_test = target.loc[target['year'] == 2026, 'result']

model = LogisticRegression(max_iter=200)
_ = model.fit(X_train, Y_train)

prob = _.predict_proba(X_train)
preds = _.predict(X_train)

acc = accuracy_score(Y_train, preds)
loss = log_loss(Y_train, prob)

print(f"World Cup 2006-2022: Accuracy: {acc:.4f}, LogLoss: {loss:.4f}")

World Cup 2006-2022: Accuracy: 0.5969, LogLoss: 0.9466

In [1344]:
# computing accuracy and loss on test set

X_train = features[(features['year'] != 2026)].drop(columns=['year'])
Y_train = target[(target['year'] != 2026)]['result']

X_test = features[(features['year'] == 2026)].drop(columns=['year'])
Y_test = target[(target['year'] == 2026)]['result']

model = LogisticRegression(max_iter=200)
_ = model.fit(X_train, Y_train)

prob = _.predict_proba(X_test)
preds = _.predict(X_test)

acc = accuracy_score(Y_test, preds)
loss = log_loss(Y_test, prob)

print(f"World Cup 2006-2022: Accuracy: {acc:.4f}, LogLoss: {loss:.4f}")

World Cup 2006-2022: Accuracy: 0.7010, LogLoss: 0.8884

In [ ]:
# Trying XGBoost
# Accuracy and loss are computed on the test set

import xgboost as xgb

X_train = features[(features['year'] != 2026)].drop(columns=['year'])
Y_train = target[(target['year'] != 2026)]['result']

X_test = features[(features['year'] == 2026)].drop(columns=['year'])
Y_test = target[(target['year'] == 2026)]['result']

model = xgb.XGBClassifier(
        objective="multi:softprob", num_class=3,
        max_depth=3, min_child_weight=10,
        subsample=0.7, colsample_bytree=0.7,
        reg_lambda=2.0, n_estimators=300,
        eval_metric="mlogloss", random_state=42,
)
model.fit(X_train, Y_train)

prob = model.predict_proba(X_train)
preds = model.predict(X_train)

acc = accuracy_score(Y_train, preds)
loss = log_loss(Y_train, prob)

print(f"World Cup 2006-2022: Accuracy: {acc:.4f} | LogLoss: {loss:.4f}")

World Cup 2006-2022: Accuracy: 0.9938 | LogLoss: 0.1418

In [ ]:
# Computing accuracy and loss on the training set

X_train = features[(features['year'] != 2026)].drop(columns=['year'])
Y_train = target[(target['year'] != 2026)]['result']

X_test = features[(features['year'] == 2026)].drop(columns=['year'])
Y_test = target[(target['year'] == 2026)]['result']

model = xgb.XGBClassifier(
        objective="multi:softprob", num_class=3,
        max_depth=3, min_child_weight=10,
        subsample=0.7, colsample_bytree=0.7,
        reg_lambda=2.0, n_estimators=300,
        eval_metric="mlogloss", random_state=42,
)
model.fit(X_train, Y_train)

prob = model.predict_proba(X_test)
preds = model.predict(X_test)

acc = accuracy_score(Y_test, preds)
loss = log_loss(Y_test, prob, labels=[0, 1, 2])

print(f"World Cup 2026: Accuracy: {acc:.4f} | LogLoss: {loss:.4f}")

# It is still incomplete: I need to make it predict only (0,1) for knockout matches
# Maybe it could help taking "stage" from "enrich_results"? Remember "enrich_results" lasts till 2018

# To be done: implementing a Random Forest
# Computing and adding the Elo and / or Fifa ranking

World Cup 2026: Accuracy: 0.7423 | LogLoss: 0.5762

In [ ]:
preds # it is predicting 2 for some knockout matches like the penultimate

array([0, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 0, 0, 2, 2, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       0, 0, 2, 1, 0, 0, 1, 1, 0, 0, 0, 2, 1, 0, 2, 0, 2, 1, 2, 1, 0, 0,
       2, 1, 2, 0, 1, 1, 0, 1, 2, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 2, 1], dtype=int64)