In [595]:
import pandas as pd

In [596]:
# Importing different datasets
path1 = r"data\results.csv"
with open(path1, encoding='UTF-8') as file:
    results = pd.read_csv(file)

path2 = r"data\train.csv"
with open(path2) as file:
    train = pd.read_csv(file)

path3 = r"data\test.csv"
with open(path3) as file:
    test = pd.read_csv(file)

path4 = r"data\shootouts.csv"
with open(path4) as file:
    shootouts = pd.read_csv(file)

path = r"data\confront_ranking.csv"
with open(path, encoding='UTF-8') as file:
    confront = pd.read_csv(file)

In [597]:
# Having a closer look at "confront"
print(confront.shape)
print(confront.columns)
print(confront.dtypes)

(23921, 25)
Index(['date', 'home_team', 'away_team', 'home_team_continent',
       'away_team_continent', 'home_team_fifa_rank', 'away_team_fifa_rank',
       'home_team_total_fifa_points', 'away_team_total_fifa_points',
       'home_team_score', 'away_team_score', 'tournament', 'city', 'country',
       'neutral_location', 'shoot_out', 'home_team_result',
       'home_team_goalkeeper_score', 'away_team_goalkeeper_score',
       'home_team_mean_defense_score', 'home_team_mean_offense_score',
       'home_team_mean_midfield_score', 'away_team_mean_defense_score',
       'away_team_mean_offense_score', 'away_team_mean_midfield_score'],
      dtype='object')
date                              object
home_team                         object
away_team                         object
home_team_continent               object
away_team_continent               object
home_team_fifa_rank                int64
away_team_fifa_rank                int64
home_team_total_fifa_points        int64
away_team_total_fifa_points        int64
home_team_score                    int64
away_team_score                    int64
tournament                        object
city                              object
country                           object
neutral_location                    bool
shoot_out                         object
home_team_result                  object
home_team_goalkeeper_score       float64
away_team_goalkeeper_score       float64
home_team_mean_defense_score     float64
home_team_mean_offense_score     float64
home_team_mean_midfield_score    float64
away_team_mean_defense_score     float64
away_team_mean_offense_score     float64
away_team_mean_midfield_score    float64
dtype: object

In [598]:
confront.tail()
# It does not have data of 2026 World Cup, so let's ignore it

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,shoot_out,home_team_result,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
23916,2022-06-14,Moldova,Andorra,Europe,Europe,180,153,932,1040,2,...,No,Win,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23917,2022-06-14,Liechtenstein,Latvia,Europe,Europe,192,135,895,1105,0,...,No,Lose,NaN,65.0,NaN,NaN,NaN,NaN,NaN,NaN
23918,2022-06-14,Chile,Ghana,South America,Africa,28,60,1526,1387,0,...,Yes,Lose,79.0,74.0,75.5,76.7,78.2,75.5,76.0,78.2
23919,2022-06-14,Japan,Tunisia,Asia,Africa,23,35,1553,1499,0,...,No,Lose,73.0,NaN,75.2,75.0,77.5,70.8,72.3,74.0
23920,2022-06-14,Korea Republic,Egypt,Asia,Africa,29,32,1519,1500,4,...,No,Win,75.0,NaN,73.0,80.0,73.8,NaN,79.3,70.8

In [599]:
# Let's see "results"
print(results.columns)
results.tail()

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49500,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,2.0,0.0,FIFA World Cup,Foxborough,United States,True
49502,2026-07-10,Spain,Belgium,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49503,2026-07-11,Norway,England,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49504,2026-07-11,Argentina,Switzerland,NaN,NaN,FIFA World Cup,Kansas City,United States,True

In [600]:
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [601]:
# Drop rows until 2006
results = results[results["date"] > "2006-01-01"]
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
29732,2006-01-02,Qatar,Libya,2.0,0.0,Friendly,Doha,Qatar,False
29733,2006-01-05,Egypt,Zimbabwe,2.0,0.0,Friendly,Alexandria,Egypt,False
29734,2006-01-07,Guinea,Togo,1.0,0.0,Friendly,Viry-Châtillon,France,True
29735,2006-01-09,Morocco,DR Congo,3.0,0.0,Friendly,Rabat,Morocco,False
29736,2006-01-11,Ghana,Togo,0.0,1.0,Friendly,Monastir,Tunisia,True

In [602]:
# Drop latest matches that are not played yet

results.loc[results.index[-3:], 'home_score'] = [2, 1, 3] # Hardcoding Quarter-finals
results.loc[results.index[-3:], 'away_score'] = [1, 2, 1]

results.dropna(inplace = True)
results.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49500,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,2.0,0.0,FIFA World Cup,Foxborough,United States,True
49502,2026-07-10,Spain,Belgium,2.0,1.0,FIFA World Cup,Inglewood,United States,True
49503,2026-07-11,Norway,England,1.0,2.0,FIFA World Cup,Miami Gardens,United States,True
49504,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,True

In [603]:
# selecting only World Cup mathces
results = results[results["tournament"] == "FIFA World Cup"]
print(results.shape)
results.tail()

(420, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49500,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,2.0,0.0,FIFA World Cup,Foxborough,United States,True
49502,2026-07-10,Spain,Belgium,2.0,1.0,FIFA World Cup,Inglewood,United States,True
49503,2026-07-11,Norway,England,1.0,2.0,FIFA World Cup,Miami Gardens,United States,True
49504,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,True

In [604]:
# Drop irrelevant columns
results.drop(columns=["tournament", "city", "country", "neutral"], inplace=True)
results.tail()

             date    home_team    away_team  home_score  away_score
49500  2026-07-07  Switzerland     Colombia         0.0         0.0
49501  2026-07-09       France      Morocco         2.0         0.0
49502  2026-07-10        Spain      Belgium         2.0         1.0
49503  2026-07-11       Norway      England         1.0         2.0
49504  2026-07-11    Argentina  Switzerland         3.0         1.0

In [605]:
# Here knockout matches which ended up at shootout are marked as draws since home_score = away_score
# Thus I need another dataset (shootouts) to deal with it
path = r"data\shootouts.csv"
with open(path) as file:
    shootouts = pd.read_csv(file)
shootouts.columns
shootouts.tail()

           date    home_team away_team       winner first_shooter
677  2026-06-06    Lithuania    Latvia    Lithuania     Lithuania
678  2026-06-29      Germany  Paraguay     Paraguay       Germany
679  2026-06-29  Netherlands   Morocco      Morocco   Netherlands
680  2026-07-03    Australia     Egypt        Egypt     Australia
681  2026-07-07  Switzerland  Colombia  Switzerland      Colombia

In [606]:
shootouts.iloc[678, 1], shootouts.iloc[678, -2]

('Germany', 'Paraguay')

In [607]:
type(shootouts.iloc[678, 1]), type(shootouts.iloc[678, -2])

(str, str)

In [608]:
shootouts.iloc[678, 1] == shootouts.iloc[678, -2]

False

In [609]:
# Transform "winner" to a binary variables as the model does not accept strings

shootouts["result"] = 1 # away_team wins
for i in range(shootouts.shape[0]):
    if shootouts.iloc[i, 3] == shootouts.iloc[i, 1]: # 3 is "winner", 1 is "home_team"
        shootouts.iloc[i, -1] = 0 # -1 is "result"
    else:
        pass
shootouts.drop(columns="winner", inplace=True)
shootouts.tail()

           date    home_team away_team first_shooter  result
677  2026-06-06    Lithuania    Latvia     Lithuania       0
678  2026-06-29      Germany  Paraguay       Germany       1
679  2026-06-29  Netherlands   Morocco   Netherlands       1
680  2026-07-03    Australia     Egypt     Australia       1
681  2026-07-07  Switzerland  Colombia      Colombia       0

In [610]:
# Considering only world cups from 2006
shootouts = shootouts[shootouts["date"] > "2006-01-01"]
shootouts.head()

           date home_team    away_team first_shooter  result
371  2006-02-04   Nigeria      Tunisia       Nigeria       0
372  2006-02-04  Cameroon  Ivory Coast      Cameroon       1
373  2006-02-10     Egypt  Ivory Coast         Egypt       0
374  2006-02-28   Finland   Kazakhstan           NaN       1
375  2006-03-01   Finland      Belarus           NaN       0

In [611]:
# dropping first_shooter as it cointains NaN values and it is the only feature related to the shootouts.
# Thus it is useless to manage NaN values of other matches just for this feature
shootouts.drop(columns="first_shooter", inplace=True)
shootouts.head()

           date home_team    away_team  result
371  2006-02-04   Nigeria      Tunisia       0
372  2006-02-04  Cameroon  Ivory Coast       1
373  2006-02-10     Egypt  Ivory Coast       0
374  2006-02-28   Finland   Kazakhstan       1
375  2006-03-01   Finland      Belarus       0

In [612]:
# Merging "results" and "shootouts"
# I didn't dropped rows relative to other comptetitions in "shootouts" as with the merge they will be gone anyway
data_matches = pd.merge(results, shootouts, left_on=["date", "home_team", "away_team"], right_on=["date", "home_team", "away_team"], how="left")
data_matches.head()

,date,home_team,away_team,home_score,away_score,result
0,2006-06-09,Germany,Costa Rica,4.0,2.0,NaN
1,2006-06-09,Poland,Ecuador,0.0,2.0,NaN
2,2006-06-10,Argentina,Ivory Coast,2.0,1.0,NaN
3,2006-06-10,England,Paraguay,1.0,0.0,NaN
4,2006-06-10,Trinidad and Tobago,Sweden,0.0,0.0,NaN

In [613]:
# testing if the merge was done correctly
data_matches[:][data_matches["date"] == "2026-06-29"]
# ok it is correct

           date    home_team away_team  home_score  away_score  result
393  2026-06-29       Brazil     Japan         2.0         1.0     NaN
394  2026-06-29      Germany  Paraguay         1.0         1.0     1.0
395  2026-06-29  Netherlands   Morocco         1.0         1.0     1.0

In [614]:
# now let's add a dummy feature to encode if the match ended up with shootout
data_matches["shootouts"] = 0
for i in range(data_matches.shape[0]):
    if data_matches.iloc[i, 3] == data_matches.iloc[i, 4]: # the two scores are even
        data_matches.iloc[i, -1] = 1 # match to shootout
    else:
        pass
data_matches.head()

,date,home_team,away_team,home_score,away_score,result,shootouts
0,2006-06-09,Germany,Costa Rica,4.0,2.0,NaN,0
1,2006-06-09,Poland,Ecuador,0.0,2.0,NaN,0
2,2006-06-10,Argentina,Ivory Coast,2.0,1.0,NaN,0
3,2006-06-10,England,Paraguay,1.0,0.0,NaN,0
4,2006-06-10,Trinidad and Tobago,Sweden,0.0,0.0,NaN,1

In [615]:
# testing if it is correct
data_matches[:][data_matches["date"] == "2026-06-29"]

,date,home_team,away_team,home_score,away_score,result,shootouts
393,2026-06-29,Brazil,Japan,2.0,1.0,NaN,0
394,2026-06-29,Germany,Paraguay,1.0,1.0,1.0,1
395,2026-06-29,Netherlands,Morocco,1.0,1.0,1.0,1

In [616]:
# managing "winner" for other matches ended in 90 mins
for i in range(data_matches.shape[0]):
    if pd.isnull(data_matches.iloc[i, -2]): # matche did not finished with shootout
        if data_matches.iloc[i, 3] > data_matches.iloc[i, 4]: # first team beated the second
            data_matches.iloc[i, -2] = 0 # home_team wins
        elif data_matches.iloc[i, 3] < data_matches.iloc[i, 4]:
            data_matches.iloc[i, -2] = 1 # away_team wins
        else:
            data_matches.iloc[i, -2] = 2 # draw
    else:
        pass
data_matches.tail(15)

,date,home_team,away_team,home_score,away_score,result,shootouts
405,2026-07-03,Australia,Egypt,1.0,1.0,1.0,1
406,2026-07-03,Argentina,Cape Verde,3.0,2.0,0.0,0
407,2026-07-03,Colombia,Ghana,1.0,0.0,0.0,0
408,2026-07-04,Canada,Morocco,0.0,3.0,1.0,0
409,2026-07-04,Paraguay,France,0.0,1.0,1.0,0
410,2026-07-05,Brazil,Norway,1.0,2.0,1.0,0
411,2026-07-05,Mexico,England,2.0,3.0,1.0,0
412,2026-07-06,Portugal,Spain,0.0,1.0,1.0,0
413,2026-07-06,United States,Belgium,1.0,4.0,1.0,0
414,2026-07-07,Argentina,Egypt,3.0,2.0,0.0,0
415,2026-07-07,Switzerland,Colombia,0.0,0.0,0.0,1
416,2026-07-09,France,Morocco,2.0,0.0,0.0,0
417,2026-07-10,Spain,Belgium,2.0,1.0,0.0,0
418,2026-07-11,Norway,England,1.0,2.0,1.0,0
419,2026-07-11,Argentina,Switzerland,3.0,1.0,0.0,0

In [617]:
# adding a new column called "stage" 
# it is important for the training part even though it will not a feature

# enrich_results lasts till 2018, so I will use other 2 datasets for 2022 and 2026
path = r"data\enrich_results.csv"
with open(path) as file:
    enrich_results = pd.read_csv(file)
enrich_results = enrich_results[["year", "stage"]]
print(enrich_results.shape)
enrich_results.head()

(900, 2)

   year    stage
0  1930  Group 1
1  1930  Group 4
2  1930  Group 2
3  1930  Group 3
4  1930  Group 1

In [618]:
path = r"data\stage_2022.csv"
with open(path) as file:
    stage_2022 = pd.read_csv(file)
stage_2022 = stage_2022[["category"]]
stage_2022.head()

  category
0  Group A
1  Group B
2  Group A
3  Group B
4  Group C

In [619]:
path = r"data\stage_2026.csv"
with open(path) as file:
    stage_2026 = pd.read_csv(file)
stage_2026 = stage_2026[["stage_id"]]
stage_2026.tail()

     stage_id
99          4
100         5
101         5
102         6
103         7

In [620]:
# dropping all rows of "enrich_results" before 2006
enrich_results = enrich_results[enrich_results["year"] >= 2006]
print(enrich_results.head())
enrich_results.drop(columns = "year", inplace=True)

     year    stage
644  2006  Group A
645  2006  Group A
646  2006  Group C
647  2006  Group B
648  2006  Group B

In [621]:
# checking if there are all the matches by checking if theire length in equal to the length of results
print(enrich_results.shape[0] + stage_2022.shape[0] + stage_2026.shape[0])
data_matches.shape[0]
# deal with it after the merge to see which matches are different

424

420

In [622]:
# Every dataset uses its own type of encoding,
# I have to make it uniformal
# 0: group stage, 1: knockouts

enrich_results.rename(columns = {"stage": "category"}, inplace=True)

enrich_results["stage"] = 1
for i in range(enrich_results.shape[0]):
    if "Group" in enrich_results.iloc[i, -2]: # -2: category
        enrich_results.iloc[i, -1] = 0 # -1: stage
    else:
        pass
print(enrich_results.iloc[:, -1].unique())
enrich_results.head()
enrich_results.drop(columns = "category", inplace=True)

[0 1]

In [623]:
# same thing for "stage_2022"

stage_2022["stage"] = 1
for i in range(stage_2022.shape[0]):
    if "Group" in stage_2022.iloc[i, -2]: # -2: category
        stage_2022.iloc[i, -1] = 0 # -1: stage
    else: 
        pass
print(stage_2022.iloc[:, -1].unique())
stage_2022.head()
stage_2022.drop(columns = "category", inplace=True)

[0 1]

In [624]:
# now let's do it for 2026
# dropping future matches
stage_2026 = stage_2026.iloc[:100, :]
stage_2026.tail()

    stage_id
95         3
96         4
97         4
98         4
99         4

In [625]:
# check lengths
print(enrich_results.shape[0] + stage_2022.shape[0] + stage_2026.shape[0])
data_matches.shape[0]
# resolved before merge

420

420

In [626]:
stage_2026["stage"] = 1
for i in range(stage_2026.shape[0]):
    if stage_2026.iloc[i, -2] == 1: # -2: stage_id
        stage_2026.iloc[i, -1] = 0 # -1: stage
    else: 
        pass
print(stage_2026.iloc[:, -1].unique())
stage_2026.head()
stage_2026.drop(columns = "stage_id", inplace=True)

[0 1]

In [627]:
stage = pd.concat((enrich_results, stage_2022, stage_2026))
stage.head()

     stage
644      0
645      0
646      0
647      0
648      0

In [628]:
print(type(stage)) # is a dataframe
# let's convert it into a Serie to attach it to "results"
stage = pd.Series(stage["stage"])
print(type(stage))
data_matches["stage"] = stage.values

data_matches.tail()

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

,date,home_team,away_team,home_score,away_score,result,shootouts,stage
415,2026-07-07,Switzerland,Colombia,0.0,0.0,0.0,1,1
416,2026-07-09,France,Morocco,2.0,0.0,0.0,0,1
417,2026-07-10,Spain,Belgium,2.0,1.0,0.0,0,1
418,2026-07-11,Norway,England,1.0,2.0,1.0,0,1
419,2026-07-11,Argentina,Switzerland,3.0,1.0,0.0,0,1

In [629]:
# Let's see "train"
print(train.shape)
train.columns
# it has some new relevant features

(192, 24)

Index(['version', 'team', 'continent', 'is_host', 'goals_scored_last_4y',
       'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y',
       'draws_last_4y', 'world_cup_titles_before',
       'squad_total_market_value_eur', 'fifa_rank_pre_tournament',
       'fifa_points_pre_tournament', 'squad_avg_age',
       'world_cup_participations_before', 'groups_passed_before',
       'round16_before', 'quarterfinals_before', 'semifinals_before',
       'finals_before', 'winner', 'finalist', 'semi_finalist',
       'quarter_finalist'],
      dtype='object')

In [630]:
# Extracting only relevant features and basic colums
# i.e. dropping the remaining
train = train.drop(columns = ["continent", "fifa_rank_pre_tournament", "fifa_points_pre_tournament", 
                             "finalist", "semi_finalist", "quarter_finalist"])
# fifa_rank_pre_torunment could have been useful but in "confront" I already have fifa rank updated at every match
train.columns

Index(['version', 'team', 'is_host', 'goals_scored_last_4y',
       'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y',
       'draws_last_4y', 'world_cup_titles_before',
       'squad_total_market_value_eur', 'squad_avg_age',
       'world_cup_participations_before', 'groups_passed_before',
       'round16_before', 'quarterfinals_before', 'semifinals_before',
       'finals_before', 'winner'],
      dtype='object')

In [631]:
# Doing same cleaning on "test" as they are the same dataset, but for different time horizons
test = test.drop(columns = ["continent", "fifa_rank_pre_tournament", "fifa_points_pre_tournament", 
                            "finalist", "semi_finalist", "quarter_finalist"])
test.columns

Index(['version', 'team', 'is_host', 'goals_scored_last_4y',
       'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y',
       'draws_last_4y', 'world_cup_titles_before',
       'squad_total_market_value_eur', 'squad_avg_age',
       'world_cup_participations_before', 'groups_passed_before',
       'round16_before', 'quarterfinals_before', 'semifinals_before',
       'finals_before', 'winner'],
      dtype='object')

In [632]:
# Merging the three datasets
# First rebuild the entire dataset from "train" and "test"
data_teams = pd.concat([train, test])
data_teams.columns, data_teams.shape

(Index(['version', 'team', 'is_host', 'goals_scored_last_4y',
        'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y',
        'draws_last_4y', 'world_cup_titles_before',
        'squad_total_market_value_eur', 'squad_avg_age',
        'world_cup_participations_before', 'groups_passed_before',
        'round16_before', 'quarterfinals_before', 'semifinals_before',
        'finals_before', 'winner'],
       dtype='object'),
 (240, 18))

In [633]:
train.iloc[22, :] # Serbia
# I have modified "test" since first it was written "Serbia and Montenegro" thus the merge did not work correctly
# and I got some NaN in df

version                                   2006
team                                    Serbia
is_host                                      0
goals_scored_last_4y                        46
goals_received_last_4y                      42
wins_last_4y                                13
losses_last_4y                              13
draws_last_4y                               12
world_cup_titles_before                      0
squad_total_market_value_eur       294500000.0
squad_avg_age                             26.9
world_cup_participations_before              9
groups_passed_before                         7
round16_before                               2
quarterfinals_before                         5
semifinals_before                            2
finals_before                                0
winner                                       0
Name: 22, dtype: object

In [634]:
test.iloc[-3, :] # Curacao
# I have modified "test" since first it was written "Cura?o" thus the merge did not work correctly
# and I got some NaN in df

version                                2026
team                               CuraÃ§ao
is_host                                   0
goals_scored_last_4y                     55
goals_received_last_4y                   39
wins_last_4y                             12
losses_last_4y                           10
draws_last_4y                            10
world_cup_titles_before                   0
squad_total_market_value_eur       25380000
squad_avg_age                          26.5
world_cup_participations_before           0
groups_passed_before                      0
round16_before                            0
quarterfinals_before                      0
semifinals_before                         0
finals_before                             0
winner                                  NaN
Name: 45, dtype: object

In [635]:
# Preparing datasets for the merge
# Extracting "year" from "date" in "data_matches"
data_matches[["year", "month", "day"]] = data_matches["date"].str.split("-", expand=True)
data_matches.drop(columns=["date"], inplace=True)
data_matches.columns

Index(['home_team', 'away_team', 'home_score', 'away_score', 'result',
       'shootouts', 'stage', 'year', 'month', 'day'],
      dtype='object')

In [636]:
# changing type of "year" in confront to match the one in "data_teams"
data_matches["year"] = pd.to_numeric(data_matches["year"])
data_matches.dtypes

home_team      object
away_team      object
home_score    float64
away_score    float64
result        float64
shootouts       int64
stage           int64
year            int64
month          object
day            object
dtype: object

In [637]:
# Merging
df = pd.merge(data_matches, data_teams, left_on=["year", "home_team"], right_on = ["version", "team"], how="left").drop(columns = ["version", "team"])
df.rename(columns={
    "is_host": "home_is_host",
    "goals_scored_last_4y": "home_goals_scored_last_4y",
    "goals_received_last_4y": "home_goals_received_last_4y", 
    "wins_last_4y": "home_wins_last_4y",
    "losses_last_4y": "home_losses_last_4y",
    "draws_last_4y": "home_draws_last_4y",
    "world_cup_titles_before": "home_wc_titles_before",
    "squad_total_market_value_eur": "home_total_market_value_eur",
    "world_cup_participations_before": "home_wc_participations_before",
    "squad_avg_age": "home_avg_age",
    "groups_passed_before": "home_groups_passed_before",
    "round16_before": "home_round16_before",
    "quarterfinals_before": "home_quarterfinals_before",
    "semifinals_before": "home_semifinals_before",
    "finals_before": "home_finals_before"
}, inplace=True)

df = pd.merge(df, data_teams, left_on=["year", "away_team"], right_on = ["version", "team"], how="left").drop(columns = ["version", "team"])
df.rename(columns={
    "is_host": "away_is_host",
    "goals_scored_last_4y": "away_goals_scored_last_4y",
    "goals_received_last_4y": "away_goals_received_last_4y", 
    "wins_last_4y": "away_wins_last_4y",
    "losses_last_4y": "away_losses_last_4y",
    "draws_last_4y": "away_draws_last_4y",
    "world_cup_titles_before": "away_wc_titles_before",
    "squad_total_market_value_eur": "away_total_market_value_eur",
    "world_cup_participations_before": "away_wc_participations_before",
    "squad_avg_age": "away_avg_age",
    "groups_passed_before": "away_groups_passed_before",
    "round16_before": "away_round16_before",
    "quarterfinals_before": "away_quarterfinals_before",
    "semifinals_before": "away_semifinals_before",
    "finals_before": "away_finals_before"
}, inplace=True)
df.columns

Index(['home_team', 'away_team', 'home_score', 'away_score', 'result',
       'shootouts', 'stage', 'year', 'month', 'day', 'home_is_host',
       'home_goals_scored_last_4y', 'home_goals_received_last_4y',
       'home_wins_last_4y', 'home_losses_last_4y', 'home_draws_last_4y',
       'home_wc_titles_before', 'home_total_market_value_eur', 'home_avg_age',
       'home_wc_participations_before', 'home_groups_passed_before',
       'home_round16_before', 'home_quarterfinals_before',
       'home_semifinals_before', 'home_finals_before', 'winner_x',
       'away_is_host', 'away_goals_scored_last_4y',
       'away_goals_received_last_4y', 'away_wins_last_4y',
       'away_losses_last_4y', 'away_draws_last_4y', 'away_wc_titles_before',
       'away_total_market_value_eur', 'away_avg_age',
       'away_wc_participations_before', 'away_groups_passed_before',
       'away_round16_before', 'away_quarterfinals_before',
       'away_semifinals_before', 'away_finals_before', 'winner_y'],
      dtype='object')

In [638]:
# Swapping columns to give them a better order
new_columns_list = ['year', 'month', 'day', 'home_team', 'away_team', 'stage', 'result', 'shootouts',
       'home_score', 'home_is_host', 'home_goals_scored_last_4y',
       'home_goals_received_last_4y', 'home_wins_last_4y', 'home_losses_last_4y', 'home_draws_last_4y', 
       'home_wc_titles_before', 'home_total_market_value_eur', 'home_avg_age', 'home_wc_participations_before', 
       'home_groups_passed_before', 'home_round16_before', 'home_quarterfinals_before', 'home_semifinals_before', 'home_finals_before',
       'away_score', 'away_is_host', 'away_goals_scored_last_4y', 'away_goals_received_last_4y',
       'away_wins_last_4y', 'away_losses_last_4y', 'away_draws_last_4y', 'away_wc_titles_before', 'away_total_market_value_eur',
       'away_avg_age', 'away_wc_participations_before', 'away_groups_passed_before',
       'away_round16_before', 'away_quarterfinals_before', 'away_semifinals_before', 'away_finals_before']
df = df[new_columns_list]

In [639]:
# checking if there are some NaN in "df"
container = list()
for j in range(df.shape[0]):
    count = 0 # counts only the first column so "container" is not too much long
    for i in df.columns:
        if count == 0:
            if df[i].isna().iloc[j]:
                count += 1
                container.append(f"Missing value at row {j} column {i}")
            else:
                pass
        else:
            pass
print(container)
print(len(container))

['Missing value at row 328 column away_is_host', 'Missing value at row 353 column away_is_host', 'Missing value at row 376 column home_is_host']
3

In [640]:
# A list of matches with some NaN at first detected by the code above,
# but then corrected directly modifing "train" and "test"

In [641]:
df.iloc[7, :]

year                                    2006
month                                     06
day                                       11
home_team                             Serbia
away_team                        Netherlands
stage                                      0
result                                   1.0
shootouts                                  0
home_score                               0.0
home_is_host                             0.0
home_goals_scored_last_4y               46.0
home_goals_received_last_4y             42.0
home_wins_last_4y                       13.0
home_losses_last_4y                     13.0
home_draws_last_4y                      12.0
home_wc_titles_before                    0.0
home_total_market_value_eur      294500000.0
home_avg_age                            26.9
home_wc_participations_before            9.0
home_groups_passed_before                7.0
home_round16_before                      2.0
home_quarterfinals_before                5.0
home_semifinals_before                   2.0
home_finals_before                       0.0
away_score                               1.0
away_is_host                             0.0
away_goals_scored_last_4y               88.0
away_goals_received_last_4y             30.0
away_wins_last_4y                       28.0
away_losses_last_4y                      7.0
away_draws_last_4y                      12.0
away_wc_titles_before                    0.0
away_total_market_value_eur      766000000.0
away_avg_age                            27.0
away_wc_participations_before            7.0
away_groups_passed_before                7.0
away_round16_before                      5.0
away_quarterfinals_before                4.0
away_semifinals_before                   3.0
away_finals_before                       2.0
Name: 7, dtype: object

In [642]:
df.iloc[20, :]

year                                    2006
month                                     06
day                                       16
home_team                          Argentina
away_team                             Serbia
stage                                      0
result                                   0.0
shootouts                                  0
home_score                               6.0
home_is_host                             0.0
home_goals_scored_last_4y               97.0
home_goals_received_last_4y             55.0
home_wins_last_4y                       31.0
home_losses_last_4y                     10.0
home_draws_last_4y                      10.0
home_wc_titles_before                    2.0
home_total_market_value_eur      777200000.0
home_avg_age                            27.8
home_wc_participations_before           13.0
home_groups_passed_before               10.0
home_round16_before                      5.0
home_quarterfinals_before                6.0
home_semifinals_before                   4.0
home_finals_before                       4.0
away_score                               0.0
away_is_host                             0.0
away_goals_scored_last_4y               46.0
away_goals_received_last_4y             42.0
away_wins_last_4y                       13.0
away_losses_last_4y                     13.0
away_draws_last_4y                      12.0
away_wc_titles_before                    0.0
away_total_market_value_eur      294500000.0
away_avg_age                            26.9
away_wc_participations_before            9.0
away_groups_passed_before                7.0
away_round16_before                      2.0
away_quarterfinals_before                5.0
away_semifinals_before                   2.0
away_finals_before                       0.0
Name: 20, dtype: object

In [643]:
df.iloc[37, :]

year                                    2006
month                                     06
day                                       21
home_team                        Ivory Coast
away_team                             Serbia
stage                                      0
result                                   0.0
shootouts                                  0
home_score                               3.0
home_is_host                             0.0
home_goals_scored_last_4y               67.0
home_goals_received_last_4y             34.0
home_wins_last_4y                       21.0
home_losses_last_4y                      8.0
home_draws_last_4y                       8.0
home_wc_titles_before                    0.0
home_total_market_value_eur      410900000.0
home_avg_age                            25.8
home_wc_participations_before            0.0
home_groups_passed_before                0.0
home_round16_before                      0.0
home_quarterfinals_before                0.0
home_semifinals_before                   0.0
home_finals_before                       0.0
away_score                               2.0
away_is_host                             0.0
away_goals_scored_last_4y               46.0
away_goals_received_last_4y             42.0
away_wins_last_4y                       13.0
away_losses_last_4y                     13.0
away_draws_last_4y                      12.0
away_wc_titles_before                    0.0
away_total_market_value_eur      294500000.0
away_avg_age                            26.9
away_wc_participations_before            9.0
away_groups_passed_before                7.0
away_round16_before                      2.0
away_quarterfinals_before                5.0
away_semifinals_before                   2.0
away_finals_before                       0.0
Name: 37, dtype: object

In [644]:
df.loc[328, :]

year                                    2026
month                                     06
day                                       14
home_team                            Germany
away_team                            Curaçao
stage                                      0
result                                   0.0
shootouts                                  0
home_score                               7.0
home_is_host                             0.0
home_goals_scored_last_4y               80.0
home_goals_received_last_4y             47.0
home_wins_last_4y                       21.0
home_losses_last_4y                     10.0
home_draws_last_4y                       7.0
home_wc_titles_before                    4.0
home_total_market_value_eur      828000000.0
home_avg_age                            26.6
home_wc_participations_before           20.0
home_groups_passed_before               18.0
home_round16_before                     10.0
home_quarterfinals_before               16.0
home_semifinals_before                  13.0
home_finals_before                       8.0
away_score                               1.0
away_is_host                             NaN
away_goals_scored_last_4y                NaN
away_goals_received_last_4y              NaN
away_wins_last_4y                        NaN
away_losses_last_4y                      NaN
away_draws_last_4y                       NaN
away_wc_titles_before                    NaN
away_total_market_value_eur              NaN
away_avg_age                             NaN
away_wc_participations_before            NaN
away_groups_passed_before                NaN
away_round16_before                      NaN
away_quarterfinals_before                NaN
away_semifinals_before                   NaN
away_finals_before                       NaN
Name: 328, dtype: object

In [645]:
df.loc[353, :]

year                                    2026
month                                     06
day                                       20
home_team                            Ecuador
away_team                            Curaçao
stage                                      0
result                                   2.0
shootouts                                  1
home_score                               0.0
home_is_host                             0.0
home_goals_scored_last_4y               39.0
home_goals_received_last_4y             23.0
home_wins_last_4y                       16.0
home_losses_last_4y                      6.0
home_draws_last_4y                      15.0
home_wc_titles_before                    0.0
home_total_market_value_eur      349580000.0
home_avg_age                            25.2
home_wc_participations_before            4.0
home_groups_passed_before                1.0
home_round16_before                      1.0
home_quarterfinals_before                0.0
home_semifinals_before                   0.0
home_finals_before                       0.0
away_score                               0.0
away_is_host                             NaN
away_goals_scored_last_4y                NaN
away_goals_received_last_4y              NaN
away_wins_last_4y                        NaN
away_losses_last_4y                      NaN
away_draws_last_4y                       NaN
away_wc_titles_before                    NaN
away_total_market_value_eur              NaN
away_avg_age                             NaN
away_wc_participations_before            NaN
away_groups_passed_before                NaN
away_round16_before                      NaN
away_quarterfinals_before                NaN
away_semifinals_before                   NaN
away_finals_before                       NaN
Name: 353, dtype: object

In [646]:
df.iloc[376, :]

year                                    2026
month                                     06
day                                       25
home_team                            Curaçao
away_team                        Ivory Coast
stage                                      0
result                                   1.0
shootouts                                  0
home_score                               0.0
home_is_host                             NaN
home_goals_scored_last_4y                NaN
home_goals_received_last_4y              NaN
home_wins_last_4y                        NaN
home_losses_last_4y                      NaN
home_draws_last_4y                       NaN
home_wc_titles_before                    NaN
home_total_market_value_eur              NaN
home_avg_age                             NaN
home_wc_participations_before            NaN
home_groups_passed_before                NaN
home_round16_before                      NaN
home_quarterfinals_before                NaN
home_semifinals_before                   NaN
home_finals_before                       NaN
away_score                               2.0
away_is_host                             0.0
away_goals_scored_last_4y               79.0
away_goals_received_last_4y             29.0
away_wins_last_4y                       27.0
away_losses_last_4y                      8.0
away_draws_last_4y                       8.0
away_wc_titles_before                    0.0
away_total_market_value_eur      370800000.0
away_avg_age                            26.6
away_wc_participations_before            3.0
away_groups_passed_before                0.0
away_round16_before                      0.0
away_quarterfinals_before                0.0
away_semifinals_before                   0.0
away_finals_before                       0.0
Name: 376, dtype: object

In [ ]:
# last look at the data before exporting
print(df.shape)
df.columns

# df.loc[(df['shootouts'] == 1) & (df['stage'] == 0), 'shootouts'] = 0
# df[(df['shootouts'] == 1) & (df['stage'] == 0)]

(420, 40)

Empty DataFrame
Columns: [year, month, day, home_team, away_team, stage, result, shootouts, home_score, home_is_host, home_goals_scored_last_4y, home_goals_received_last_4y, home_wins_last_4y, home_losses_last_4y, home_draws_last_4y, home_wc_titles_before, home_total_market_value_eur, home_avg_age, home_wc_participations_before, home_groups_passed_before, home_round16_before, home_quarterfinals_before, home_semifinals_before, home_finals_before, away_score, away_is_host, away_goals_scored_last_4y, away_goals_received_last_4y, away_wins_last_4y, away_losses_last_4y, away_draws_last_4y, away_wc_titles_before, away_total_market_value_eur, away_avg_age, away_wc_participations_before, away_groups_passed_before, away_round16_before, away_quarterfinals_before, away_semifinals_before, away_finals_before]
Index: []

[0 rows x 40 columns]

In [659]:
df.to_csv(r"data\dataset.csv", index=False)